source 'https://cdn.cocoapods.org/'

platform :ios, '9.0'

target 'PicovoiceAppTest' do
    pod 'Picovoice-iOS', '~> 2.1.1'
end

target 'PicovoiceAppTestUITests' do    
    pod 'Picovoice-iOS', '~> 2.1.1'
end
