[package]
name = "picovoice_micdemo"
version = "3.0.4"
edition = "2018"

[dependencies]
chrono = "0.4.19"
clap = "3.2.3"
ctrlc = "3.1.9"
hound = "3.4.0"
itertools = "0.10.3"
# picovoice =  "=3.0.4"
picovoice = { path = "../../../sdk/rust" }
pv_recorder = "=1.2.2"
