source 'https://cdn.cocoapods.org/'

platform :ios, '9.0'

target 'BaristaDemo' do    
    pod 'Picovoice-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/picovoice/v2.0/sdk/ios/Picovoice-iOS.podspec'

    # delete
    pod 'Rhino-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/rhino/v2.0/binding/ios/Rhino-iOS.podspec'
    pod 'Porcupine-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/porcupine/v2.0/binding/ios/Porcupine-iOS.podspec'
end