name: Run filedemo

inputs:
  access-key:
    required: true
  platform:
    required: true
  arch:
    required: true
  ext:
    default: so
  lang:
    required: true
  lang-ext:
    required: true
  keyword_file: 
    required: true
  context_file:
    required: true
  audio_file:
    required: true

runs:
  using: "composite"
  steps:
  - run: >
      ./build/picovoice_demo_file
      -a ${{ inputs.access-key }}
      -l ../../sdk/c/lib/${{ inputs.platform }}/${{ inputs.arch }}/libpicovoice.${{ inputs.ext }}
      -p ../../resources/porcupine/lib/common/porcupine_params${{ inputs.lang-ext }}.pv
      -k '../../resources/porcupine/resources/keyword_files${{ inputs.lang-ext }}/${{ inputs.platform }}/${{ inputs.keyword_file }}_${{ inputs.platform }}.ppn'
      -r ../../resources/rhino/lib/common/rhino_params${{ inputs.lang-ext }}.pv
      -c '../../resources/rhino/resources/contexts${{ inputs.lang-ext }}/${{ inputs.platform }}/${{ inputs.context_file }}_${{ inputs.platform }}.rhn'
      --porcupine_sensitivity 0.5
      --rhino_sensitivity 0.5
      -w ../../resources/audio_samples/${{ inputs.audio_file }}.wav
    working-directory: demo/c
    shell: bash
  