name: Run filedemo

inputs:
  access_key:
    required: true
  library_path:
    required: true
  ppn_model_path:
    required: true
  keyword_path:
    required: true
  rhn_model_path:
    required: true
  context_path:
    required: true
  ppn_sensitivity:
    default: 0.5
  rhn_sensitivity:
    default: 0.5
  require_endpoint:
    default: "true"
  audio_path:
    required: true

runs:
  using: "composite"
  steps:
  - run: >
      ./build/picovoice_demo_file
      -a ${{ inputs.access_key }}
      -l ${{ inputs.library_path }}
      -p ${{ inputs.ppn_model_path }}
      -k ${{ inputs.keyword_path }}
      -r ${{ inputs.rhn_model_path }}
      -c ${{ inputs.context_path }}
      --porcupine_sensitivity ${{ inputs.ppn_sensitivity }}
      --rhino_sensitivity ${{ inputs.rhn_sensitivity }}
      --require_endpoint ${{ inputs.require_endpoint }}
      -w ${{ inputs.audio_path }}
    working-directory: demo/c
    shell: bash
  