source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'

target 'PicovoiceBackgroundServiceDemo' do
    pod 'Porcupine-iOS', '~> 3.0.0'
    pod 'Rhino-iOS', '~> 3.0.0'
    pod 'Picovoice-iOS', '~> 3.0.0'
    pod 'SwiftySound'
end
