name: .NET Codestyle

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**/dotnet/*.cs'
      - '.github/workflows/dotnet-codestyle.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - '**/dotnet/*.cs'
      - '.github/workflows/dotnet-codestyle.yml'

jobs:
  check-dotnet-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Run Binding Codestyle
      run: dotnet format --verify-no-changes --no-restore
      working-directory: sdk/dotnet

      # ************** REMOVE AFTER RELEASE ********************
    - name: Pack .NET SDK
      run: dotnet pack -c Release
      working-directory: sdk/dotnet

    - name: Add local NuGet package file
      continue-on-error: true
      run: dotnet add package -s ../../../sdk/dotnet/Picovoice/bin/Release Picovoice
      working-directory: demo/dotnet/PicovoiceDemo
      # ********************************************************

    - name: Run Demo Codestyle
      run: dotnet format --verify-no-changes --no-restore
      working-directory: demo/dotnet
