name: Flutter

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/flutter.yml'
      - 'demo/flutter/**'
      - '!demo/flutter/README.md'
      - 'demo/flutter-clock/**'
      - '!demo/flutter-clock/README.md'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/flutter.yml'
      - 'demo/flutter/**'
      - '!demo/flutter/README.md'
      - 'demo/flutter-clock/**'
      - '!demo/flutter-clock/README.md'

defaults:
  run:
    working-directory: demo/flutter

jobs:
  build-android:
    name: Build Android demo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-version: ['3.0.4', '3.22.2']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Flutter ${{ matrix.flutter-version }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ matrix.flutter-version }}

    - name: Install dependencies
      run: flutter pub get

    - name: Prepare demo
      run: dart scripts/prepare_demo.dart en

    - name: Build
      run: flutter build apk

  build-ios:
    name: Build iOS demo
    runs-on: macos-12
    strategy:
      matrix:
        flutter-version: ['2.10.0', '3.0.4', '3.22.2']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Flutter ${{ matrix.flutter-version }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ matrix.flutter-version }}
        architecture: x64

    - name: Update Cocoapods repo
      run: pod repo update

    - name: Install dependencies
      run: flutter pub get

    - name: Prepare demo
      run: dart scripts/prepare_demo.dart en

    - name: Build
      run: flutter build ios --release --no-codesign

  build-clock-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/flutter-clock

    strategy:
      matrix:
        flutter-version: ['2.10.0', '3.0.4', '3.22.2']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Flutter ${{ matrix.flutter-version }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ matrix.flutter-version }}

    - name: Install dependencies
      run: flutter pub get

    - name: Prepare demo
      run: ./copy.sh

    - name: Build
      run: flutter build apk

  build-clock-ios:
    runs-on: macos-12
    defaults:
      run:
        working-directory: demo/flutter-clock

    strategy:
      matrix:
        flutter-version: ['2.10.0', '3.0.4', '3.22.2']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Flutter ${{ matrix.flutter-version }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ matrix.flutter-version }}
        architecture: x64

    - name: Update Cocoapods repo
      run: pod repo update

    - name: Install dependencies
      run: flutter pub get

    - name: Prepare demo
      run: ./copy.sh

    - name: Build
      run: flutter build ios --release --no-codesign
