name: Go Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/go/**'
      - '!demo/go/README.md'
      - '.github/workflows/go-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/go/**'
      - '!demo/go/README.md'
      - '.github/workflows/go-demos.yml'

defaults:
  run:
    working-directory: demo/go

jobs:
  build-micdemo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.16', '1.17', '1.18', '1.19', '1.20', 'stable' ]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Mingw
      uses: egor-tensin/setup-mingw@v2
      if: ${{ (matrix.os == 'windows-latest') && (matrix.go != 'stable') && (matrix.go < 1.20) }}
      with:
        version: 11.2.0

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Build micdemo
      run: go build
      working-directory: demo/go/micdemo

  build-filedemo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.16', '1.17', '1.18', '1.19', '1.20', 'stable' ]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Mingw
      uses: egor-tensin/setup-mingw@v2
      if: ${{ (matrix.os == 'windows-latest') && (matrix.go != 'stable') && (matrix.go < 1.20) }}
      with:
        version: 11.2.0

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Build filedemo
      run: go build
      working-directory: demo/go/filedemo
