name: Go Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/go/**'
      - '!demo/go/README.md'
      - '.github/workflows/go-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/go/**'
      - '!demo/go/README.md'
      - '.github/workflows/go-demos.yml'

defaults:
  run:
    working-directory: demo/go

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        go: [ '1.16', '1.17', '1.18', '1.19', '1.20', 'stable' ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Mingw
      uses: egor-tensin/setup-mingw@v2
      if: ${{ (matrix.os == 'windows-latest') && (matrix.go != 'stable') && (matrix.go < 1.20) }}
      with:
        version: 11.2.0

    - name: Set up go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

      # ************** REMOVE AFTER RELEASE ********************
    - name: Install Go SDK from branch
      run: go get github.com/Picovoice/picovoice/sdk/go/v3/@98eed548c1219c0bf9619550434dd5f457b6a090
      # ********************************************************

    - name: Build micdemo
      run: go build micdemo/picovoice_mic_demo.go

    - name: Build filedemo
      run: go build filedemo/picovoice_file_demo.go

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [ rpi3-32, rpi3-64, rpi4-32, rpi4-64, rpi5-64 ]

    steps:
    - uses: actions/checkout@v3

      # ************** REMOVE AFTER RELEASE ********************
    - name: Install Go SDK from branch
      run: go get github.com/Picovoice/picovoice/sdk/go/v3/@98eed548c1219c0bf9619550434dd5f457b6a090
      # ********************************************************

    - name: Build micdemo
      run: go build micdemo/picovoice_mic_demo.go

    - name: Build filedemo
      run: go build filedemo/picovoice_file_demo.go
