name: Go

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/go.yml'
      - 'sdk/go/**'
      - '!sdk/go/README.md'
      - 'resources/.test/**'
      - 'resources/audio_samples/**'
      - 'resources/porcupine'
      - 'resources/rhino'

  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/go.yml'
      - 'sdk/go/**'
      - '!sdk/go/README.md'
      - 'resources/.test/**'
      - 'resources/audio_samples/**'
      - 'resources/porcupine'
      - 'resources/rhino'

defaults:
  run:
    working-directory: sdk/go

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: [ '1.16', '1.17', '1.18' ]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: go get

    - name: Build
      run: go build

    - name: Test
      run: go test -access_key ${{secrets.PV_VALID_ACCESS_KEY}}

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi2, rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson, beaglebone]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: go get

    - name: Build
      run: go build

    - name: Test
      run: go test -access_key ${{secrets.PV_VALID_ACCESS_KEY}}
