name: Go

on:
  workflow_dispatch:
  push:
    branches: [ master, lib-update ]
    paths:
      - 'sdk/go/**'
      - '!sdk/go/README.md'
      - 'resources/porcupine'
      - 'resources/rhino'
      - '.github/workflows/go.yml'
  pull_request:
    branches: [ master, lib-update ]
    paths:
      - 'sdk/go/**'
      - '!sdk/go/README.md'
      - 'resources/porcupine'
      - 'resources/rhino'
      - '.github/workflows/go.yml'

defaults:
  run:
    working-directory: sdk/go

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: [ '1.16', '1.17' ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: go get

    - name: Build
      run: go build

    - name: Test
      run: go test -access_key ${{secrets.PV_VALID_ACCESS_KEY}}

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi2, rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson, beaglebone]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: go get

    - name: Build
      run: go build

    - name: Test
      run: go test -access_key ${{secrets.PV_VALID_ACCESS_KEY}}
