name: Go

on:
  push:
    branches: [ github-actions ]
    paths:
      - 'DELETEME.TXT'
      - 'binding/go/**'
      - '!binding/go/README.md'
  pull_request:
    branches: [ github-actions ]
    paths:
      - 'DELETEME.TXT'
      - 'binding/go/**'
      - '!binding/go/README.md'

defaults:
  run:
    working-directory: binding/go

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.16' ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Pre-build dependencies
      run: ./copy.sh

    - name: Install dependencies
      run: go get

    - name: Build
      run: go build

    - name: Test
      run: go test
