name: Go

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'sdk/go/**'
      - '!sdk/go/README.md'
      - 'resources/porcupine'
      - 'resources/rhino'

  pull_request:
    branches: [ master ]
    paths:
      - 'sdk/go/**'
      - '!sdk/go/README.md'
      - 'resources/porcupine'
      - 'resources/rhino'

defaults:
  run:
    working-directory: sdk/go

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.16', '1.17' ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: go get

    - name: Build
      run: go build

    - name: Test
      run: go test -access_key ${{secrets.PV_VALID_ACCESS_KEY}}
