name: iOS BrowserStack Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/ios-browserstack.yml'
      - 'sdk/ios/PicovoiceAppTest/**'
      - 'resources/audio_samples/**'
      - 'resources/porcupine'
      - 'resources/rhino'
      - 'resources/.test/**'
  pull_request:
    branches: [ ios-bitcode-spm, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/ios-browserstack.yml'
      - 'sdk/ios/PicovoiceAppTest/**'
      - 'resources/audio_samples/**'
      - 'resources/porcupine'
      - 'resources/rhino'
      - 'resources/.test/**'

defaults:
  run:
    working-directory: sdk/ios/PicovoiceAppTest

jobs:
  build:
    name: Run iOS Tests on BrowserStack
    runs-on: macos-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run:
          pip3 install requests

      - name: Make build dir
        run: mkdir .ddp

      - name: Copy test_resources
        run: ./copy_test_resources.sh

      - name: Inject AccessKey
        run: sed -i '.bak' 's:{TESTING_ACCESS_KEY_HERE}:${{secrets.PV_VALID_ACCESS_KEY}}:'
          PicovoiceAppTestUITests/BaseTest.swift

      - name: XCode Build
        run: xcrun xcodebuild build-for-testing
          -configuration Debug
          -project PicovoiceAppTest.xcodeproj
          -sdk iphoneos
          -scheme PicovoiceAppTest
          -derivedDataPath .ddp
          CODE_SIGNING_ALLOWED=NO

      - name: Generating ipa
        run: cd .ddp/Build/Products/Debug-iphoneos/ &&
          mkdir Payload &&
          cp -r PicovoiceAppTest.app Payload &&
          zip --symlinks -r PicovoiceAppTest.ipa Payload &&
          rm -r Payload

      - name: Zipping Tests
        run: cd .ddp/Build/Products/Debug-iphoneos/ &&
          zip --symlinks -r PicovoiceAppTestUITests.zip PicovoiceAppTestUITests-Runner.app

      - name: Run tests on BrowserStack
        run: python3 ../../../script/automation/browserstack.py
          --type xcuitest
          --username "${{secrets.BROWSERSTACK_USERNAME}}"
          --access_key "${{secrets.BROWSERSTACK_ACCESS_KEY}}"
          --project_name "Picovoice-iOS"
          --devices "ios-min-max"
          --app_path ".ddp/Build/Products/Debug-iphoneos/PicovoiceAppTest.ipa"
          --test_path ".ddp/Build/Products/Debug-iphoneos/PicovoiceAppTestUITests.zip"
