name: Java Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/java-demos.yml'
      - 'demo/java/**'
      - '!demo/java/README.md'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/java-demos.yml'
      - 'demo/java/**'
      - '!demo/java/README.md'

defaults:
  run:
    working-directory: demo/java

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          platform: linux
        - os: windows-latest
          platform: windows
        - os: macos-latest
          platform: mac

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build
      run: ./gradlew build

    - name: Run filedemo
      run: java -jar build/libs/picovoice-file-demo.jar
        -a  ${{ secrets.PV_VALID_ACCESS_KEY }}
        -i ../../resources/audio_samples/picovoice-coffee.wav
        -k ../../resources/porcupine/resources/keyword_files/${{ matrix.platform }}/picovoice_${{ matrix.platform }}.ppn
        -c ../../resources/rhino/resources/contexts/${{ matrix.platform }}/coffee_maker_${{ matrix.platform }}.rhn

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi2, rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson, beaglebone]
        include:
        - machine: rpi2
          platform: raspberry-pi
        - machine: rpi3-32
          platform: raspberry-pi
        - machine: rpi3-64
          platform: raspberry-pi
        - machine: rpi4-32
          platform: raspberry-pi
        - machine: rpi4-64
          platform: raspberry-pi
        - machine: jetson
          platform: jetson
        - machine: beaglebone
          platform: beaglebone

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: ./gradlew build

    - name: Run filedemo
      run: java -jar build/libs/picovoice-file-demo.jar
        -a  ${{ secrets.PV_VALID_ACCESS_KEY }}
        -i ../../resources/audio_samples/picovoice-coffee.wav
        -k ../../resources/porcupine/resources/keyword_files/${{ matrix.platform }}/picovoice_${{ matrix.platform }}.ppn
        -c ../../resources/rhino/resources/contexts/${{ matrix.platform }}/coffee_maker_${{ matrix.platform }}.rhn