name: Java

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/java.yml'
      - 'sdk/java/**'
      - '!sdk/java/README.md'
      - 'resources/audio_samples/**'
      - 'resources/porcupine'
      - 'resources/rhino'
      - 'resources/test/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/java.yml'
      - 'sdk/java/**'
      - '!sdk/java/README.md'
      - 'resources/audio_samples/**'
      - 'resources/porcupine'
      - 'resources/rhino'
      - 'resources/test/**'

defaults:
  run:
    working-directory: sdk/java

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew test -DpvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}"

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi2, rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson, beaglebone]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew test -DpvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}"
