name: Java

on:
  workflow_dispatch:
  push:
    branches: [ master, v2.0 ]
    paths:
      - 'sdk/java/**'
      - '!sdk/java/README.md'
  pull_request:
    branches: [ master, v2.0 ]
    paths:
      - 'sdk/java/**'
      - '!sdk/java/README.md'

defaults:
  run:
    working-directory: sdk/java

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Java dependencies pre-build
      run: ./gradlew assemble
      working-directory: resources/porcupine/binding/java

    - name: Java dependencies pre-build
      run: ./gradlew assemble
      working-directory: resources/rhino/binding/java

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew test -DpvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}"
