name: Vue Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/vue/**'
      - '!demo/vue/README.md'
      - '.github/workflows/vue-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/vue/**'
      - '!demo/vue/README.md'
      - '.github/workflows/vue-demos.yml'

defaults:
  run:
    working-directory: demo/vue

jobs:
  build-demos:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Pre-build dependencies
      run: npm install yarn
      
    - name: Build Local Porcupine Web SDK
      run: yarn && yarn copywasm && yarn copyppn && yarn build
      working-directory: resources/porcupine/binding/web
      
    - name: Build Local Rhino Web SDK
      run: yarn && yarn copywasm && yarn build
      working-directory: resources/rhino/binding/web
      
    - name: Build Local SDK
      run: yarn && yarn build
      working-directory: sdk/web

    - name: Build Local Vue SDK
      run: yarn && yarn build
      working-directory: sdk/vue

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build en

    - name: Build another language
      run: yarn build ja
