name: Web Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/web/**'
      - '!demo/web/README.md'
      - '.github/workflows/web-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/web/**'
      - '!demo/web/README.md'
      - '.github/workflows/web-demos.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/web

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Install dependencies
      run: yarn install
  
  build-electron:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/electron

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Node.js lts/*
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Install dependencies
      run: yarn install

    - name: Build application
      run: yarn build
