name: Web Codestyle

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**/web/*.js'
      - '**/web/*.ts'
      - '.github/workflows/web-codestyle.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - '**/web/*.js'
      - '**/web/*.ts'
      - '.github/workflows/web-codestyle.yml'

jobs:
  check-web-codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Local Porcupine dependency
        run: yarn && yarn copywasm && yarn copyppn && yarn build
        working-directory: resources/porcupine/binding/web

      - name: Local Rhino dependency
        run: yarn && yarn copywasm && yarn build
        working-directory: resources/rhino/binding/web

      - name: Pre-build dependencies
        run: npm install yarn

      - name: Run Binding Linter
        run: yarn && yarn lint
        working-directory: sdk/web
